### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by dx616b** [shibatch/cputemp#1]
From where does the app read the cpu - frequency ?

I have tried and tested but only once I got it running and throttling the cpu by only running it not as daemon. 

Systemd or daemon from cli does not work for me.

Tested on proxmox 8.3

How to debug ?

**Comment by shibatch** [comment]
Hello,

Thank you for using cputemp.
First, you need to run cputemp with no argument.
Then you will see a list of available sensors.
If you attach the results of running cputemp without arguments, I may be able to advise you.
Please also tell me your CPU and kernel version.

**Comment by dx616b** [comment]
Hello,

########
Version:

uname -a
Linux lenovo 6.8.12-5-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-5 (2024-12-03T10:26Z) x86_64 GNU/Linux

CPU: Xeon e3-1275L

########
I am using it by using this service (which works for me)

cat /etc/systemd/system/cputemp.service

[Unit]
Description=CPU Temperature Monitor
After=network.target

[Service]
ExecStart=/usr/bin/cputemp --sensor coretemp --period 1 --temp 75 --verbose
Restart=always
User=root
StandardOutput=append:/var/log/cputemp.log
StandardError=append:/var/log/cputemp_error.log

[Install]
WantedBy=multi-user.target


##########
But I could not make it work as daemon.

Cputemp:

cputemp
Usage : cputemp [<options>]

This utility controls the CPU frequency to make its temperature close to the target

Options :
  --sensor <sensor name>         Specify sensor name
  --period <seconds>             Specify period
  --temp <target temperature>    Specify target CPU temperature
  --daemon <pid file name>       Daemonize
  --kill-daemon <pid file name>  Kill already running daemon
  --verbose                      Turn on verbose mode

Available sensors : acpitz ( 27.8 C), acpitz ( 29.8 C), x86_pkg_temp ( 43 C), acpitz (27.8 C), coretemp (42 C), it8792 (39 C),

**Comment by shibatch** [comment]
I had never heard of the Linux lenovo kernel, but is it the one mentioned in the article below?

https://www.phoronix.com/news/Lenovo-Linux-Ultra-Performance

Assuming that ACPI-related patches have been applied, it is possible that the cpufreq functionality has been changed.

If possible, try changing to a kernel that has not been patched by lenovo.

**Comment by dx616b** [comment]
root@lenovo:~# uname --kernel-name
Linux
root@lenovo:~# uname --kernel-release
6.8.12-5-pve
root@lenovo:~# uname --kernel-version
#1 SMP PREEMPT_DYNAMIC PMX 6.8.12-5 (2024-12-03T10:26Z)

Hey, i think that Lenovo is the hostname :) 

Anyway thanks, it works for me without needing the daemon.

Great app btw 👍

**Comment by shibatch** [comment]
Wait a minute, is the problem solved?

**Comment by dx616b** [comment]
Technically for me it works using the service file I mentioned above. Is not needed to use a pid at all, systemd manages it.
Plus you have logs that you can see if in any point of time this app has throttled the CPU.

**Comment by shibatch** [comment]
I think the log file would become huge with that configuration.
But I'm glad you solved the problem.

**Comment by dx616b** [comment]
I thought about that and will append in logs only if **scaling_max_freq** is less than **max of my cpu** or when **cpu_temp** is **over threshold**.
or add the file as part of logrotate but need to check it.
